### PR TITLE
Add Debian 12 as main distribution

### PR DESCRIPTION
**Pull request by MisterDA**

### CODE REVIEW

**Comment by avsm** [comment]
This is a big change to opam-repo-ci; before it goes live there, could you please post a headsup to discuss.ocaml.org that the main build matrix is moving forward to the new stable distro (and/or a brief post for infra.ocaml.org)?

**Comment by tmcgilchrist** [comment]
Should we stop debian 10 builds at the same time? EOL was last year but LTS continues to 2024.
Screenshot 2023-06-23 at 10 47 21

**Comment by avsm** [comment]
It's reasonable to keep Debian 10 going till LTS just because so many downstream packagers use it. However, it's time to trim the other distros. Please see https://github.com/ocurrent/ocaml-dockerfile/pull/176

**Comment by avsm** [comment]
I've posted to discuss about raising the minimum OCaml version as well; https://discuss.ocaml.org/t/raising-the-minimum-tested-version-of-ocaml-to-4-05-or-4-11-from-4-02/12464

**Comment by tmcgilchrist** [comment]
Thanks for doing both those things.
I’ll review and update things when I get back to my computer.

**Comment by tmcgilchrist** [comment]
Post here https://github.com/ocaml/infrastructure/pull/54 about Debian 12 and deprecating other distributions. @avsm 

Based on the feedback on that discuss thread, I think we could move to 4.08 being the lowest supported version.  I'll prep a PR for it next week.

**Comment by tmcgilchrist** [comment]
Included in https://github.com/ocurrent/docker-base-images/pull/237

**Pull request closed without merging**
