### PR TITLE
Add CentOS SCL in for CentOS7 base image

### PR DESCRIPTION
**Pull request by avsm**
This in turn allows us to get Cargo installed for
https://github.com/ocaml/opam-repository/pull/17827

### CODE REVIEW

**Comment by talex5** [comment]
Doesn't compile!

**Comment by avsm** [comment]
Oops, did the usual "forget to commit in the submodule". Now updated.

**Comment by talex5** [comment]
Doesn't work:

```
================================================================================
 Package                    Arch        Version               Repository   Size
================================================================================
Installing:
 centos-release-scl         noarch      2-3.el7.centos        extras       12 k
Installing for dependencies:
 centos-release-scl-rh      noarch      2-3.el7.centos        extras       12 k

Transaction Summary
================================================================================
Install  1 Package (+1 Dependent package)

Total download size: 24 k
Installed size: 39 k
Is this ok [y/d/N]: Exiting on user command
Your transaction was saved, rerun it with:
 yum load-transaction /tmp/yum_save_tx.2020-12-16.10-48.ulaC6o.yumtx
The command '/bin/sh -c yum install centos-release-scl' returned a non-zero code: 1
```

**Comment by talex5** [comment]
(note: I also rebased on `master` to fix the lint problem)

**Comment by avsm** [comment]
Sorry, pushed a proper fix. Take 3 for distracted hacking :-)

**Comment by avsm** [comment]
Terribly sorry, I just can't get this right. I put it into the opam image instead of the compiler images. Fixing...

**Comment by talex5** [comment]
Is this working now? It can be merged if so, but not sure how to test it.

**Comment by avsm** [comment]
Not yet; I'm just figuring out the runes to persistently enable SCL repos.

**Comment by talex5** [comment]
(I've rebased your branch to `master` so I can deploy the logging change)

**Comment by avsm** [comment]
I'll come back to this some other time. It needs major surgery in order to persist the choice of SCL packages.

**Pull request closed without merging**
