### PR TITLE
add ocaml 4.14-dev, opensuse-15.3, deprecate ubuntu 20.10

### PR DESCRIPTION
**Pull request by avsm**

### CODE REVIEW

**Comment by avsm** [comment]
pushed to live

**Comment by avsm** [comment]
xref https://github.com/ocaml/opam-repository/pull/18784

**Comment by avsm** [comment]
Seems to be working fine for the new builds

**Comment by talex5** [comment]
It says:
```
Step 4/9 : RUN opam switch create 4.14 --packages=ocaml-variants.4.14.0+trunk
 ---> Running in 40e9cda350cd
[ERROR] ocaml-variants = 4.14.0+trunk no matching version
```
https://base-images.ocamllabs.io/job/2021-06-03/130902-ocluster-build-cf6e1e

**Comment by avsm** [comment]
Darn it all!

**Comment by avsm** [comment]
@talex5 that was from before I refreshed the git checkout. Its working fine on the current run:

```
$ docker run -it ocurrent/opam-staging:debian-testing-ocaml-4.14-amd64 ocaml -version
Unable to find image 'ocurrent/opam-staging:debian-testing-ocaml-4.14-amd64' locally
debian-testing-ocaml-4.14-amd64: Pulling from ocurrent/opam-staging
420047682034: Pull complete 
c5ae9b730a89: Pull complete 
8bcf8eaf9749: Pull complete 
Digest: sha256:a487cf7e4ba00561f33959c62078373876edb175e4dfc701617d72791aa63278
Status: Downloaded newer image for ocurrent/opam-staging:debian-testing-ocaml-4.14-amd64
The OCaml toplevel, version 4.14.0+dev0-2021-06-03
```

**Comment by talex5** [comment]
Oh, OK!

**Pull request merged**
