### PR TITLE
Revert #112

### PR DESCRIPTION
**Pull request by kit-ty-kate**
The fix for https://github.com/ocaml/opam/issues/4682 is now merged and it is safe to resume with opam master

### CODE REVIEW

**Review by talex5 — APPROVED** [review]
Looks good. GitHub seems to be having some trouble at the moment, which might explain why CI didn't run.

**Comment by talex5** [comment]
@avsm : I see a "do not build a 4.10 multicore anymore, just 4.12" commit on `live`, but I don't see a PR for it. Do you want to keep that?

**Comment by kit-ty-kate** [comment]
I can't fully test this locally (I don't have the credentials for docker.io/ocurrent/opam-staging) but I tested the best I could using the first stage image and it works as expected.

**Comment by avsm** [comment]
I want to keep that; Ill reconcile the branches now @talex5. thanks for the tests to date kate!

**Pull request merged**
