### PR TITLE
Make --submission-service optional

### PR DESCRIPTION
**Pull request by dra27**
Split off from #65, as it's not related.

### CODE REVIEW

**Comment by avsm** [comment]
Isn't it better to make this an `option` type and to do a local `docker build` instead of `Current_ocluster.Raw.build_and_push` (in src/pipeline.ml)? Making a fake uri like this will just make the local pipeline fail.

**Comment by dra27** [comment]
In this instance, the pipeline failing is the "desired" outcome - I was seeking to update the tutorial where what you're after is simply the graph of what will be built (everything up to "However, before going further you will need to configure the builders." in the README)

**Comment by talex5** [comment]
Alternative suggestion: provide a `docker-compose.yml` that brings up the base image builder and a local OCluster scheduler. The pipeline can connect to that without showing any errors, but the builds will just wait because there are no workers. But the user can later connect their own workers to it if they want to try building.

**Comment by talex5** [comment]
I've added a docker-compose file in https://github.com/ocurrent/docker-base-images/pull/82 as suggested. It should now be possible to see the graph and also to run builds easily.

**Pull request closed without merging**
