### PR TITLE
CentOS 8 is EOL since 31/12/2021

### PR DESCRIPTION
**Pull request by kit-ty-kate**
See https://github.com/avsm/ocaml-dockerfile/pull/88
Fixes https://github.com/ocurrent/docker-base-images/issues/157

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
@dra27 mmh, it looks like ocaml-dockerfile’s `master` and the ocaml-dockerfile submodule here are out of sync

**Comment by dra27** [comment]
Yeah, we're piling up with stuff at the moment. It's so weird to have CentOS 8 EOL before CentOS 7 but 🤷‍♂️

**Comment by dra27** [comment]
Aiming to get #153 merged and then stack this one up afterwards (and before the weekly pull on Saturday)

**Comment by dra27** [comment]
With rebasing, this is actually merged as part of #153, thanks!

**Pull request closed without merging**
