### PR TITLE
Run opam init in OS base image

### PR DESCRIPTION
**Pull request by dra27**
Split off from #65

### CODE REVIEW

**Comment by talex5** [comment]
It's live and building images now: https://base-images.ocamllabs.io/

**Comment by dra27** [comment]
Be very afraid 😈

**Comment by kit-ty-kate** [comment]
This change just broke opam-health-check as it's using the base image with opam 2.1 and now requires user input to upgrade the `~/.opam` directory
```
Step 19/22 : RUN opam switch create --repositories=alpha,beta,default 4.11.1
 ---> Running in 13933edfa09d
This development version of opam requires an update to the layout of /home/opam/.opam from version 2.0 to version 2.1, which can't be reverted.
You may want to back it up before going further.
Continue? [Y/n] n
```
it's not a big deal but just so you know for next time.

**Comment by dra27** [comment]
If opam-health-check’s overriding opam, would it be better for it to be using an image at an earlier stage of the pipeline? Or should there therefore be an earlier stage? Each compiler container having to init opam itself ground my poor mechanical disk to a halt 🙂

**Comment by kit-ty-kate** [comment]
It's ok I just fixed it in https://github.com/kit-ty-kate/opam-health-check/commit/baaa4fdd20150f5efe878faebb26e3a9d2402d2c. It's not too much of a bother to me since I only do this step once.
However I was surprised by the behaviour of opam init there so I opened an issue: https://github.com/ocaml/opam/issues/4409

**Pull request merged**
