### PR TITLE
Switch all uses of the git:// protocol to https:// (Github disabled git://)

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Applies https://github.com/avsm/ocaml-dockerfile/pull/73

https://github.blog/2021-09-01-improving-git-protocol-security-github/

### CODE REVIEW

**Review by talex5 — COMMENTED** [review]
Thanks! The images have now been updated, so it should be possible to remove the tmp hack and just use a newer base image.

**Comment by kit-ty-kate** [comment]
> The images have now been updated, so it should be possible to remove the tmp hack and just use a newer base image.

Done

**Review by talex5 — APPROVED** [review]
Thanks - this is ready to merge once https://github.com/avsm/ocaml-dockerfile/pull/73 is merged.

**Comment by dra27** [comment]
Thanks!

**Comment by dra27** [comment]
live also force-pushed to remove the deployer workaround

**Pull request merged**
