### PR TITLE
Make 0install-solver available in the opam 2.1 installation

### PR DESCRIPTION
**Pull request by kit-ty-kate**

### CODE REVIEW

**Comment by talex5** [comment]
Looks like this depends on a commit that isn't merged yet.

**Comment by kit-ty-kate** [comment]
yes, it's on purpose, I remember @avsm saying starting with docker-base-images is better to avoid issues, at the last meeting

**Comment by avsm** [comment]
Yep, that's right. It's best to ensure things build here and then merge them (immediately) since we dont have a CI-for-the-CI. I'm just doing the multicore changes and then will look at this...

**Comment by avsm** [comment]
@kit-ty-kate wouldn't this be better as a patch to opam itself?  I'm a little unclear on what's going on here -- we install the external 0install solver, and then it becomes available to opam as builtin-0install?

**Comment by kit-ty-kate** [comment]
The required PR in opam has now been merged so this PR is now ready to be reviewed.

**Comment by talex5** [comment]
The ocaml-dockerfile PR needs rebasing on master before we can push this to `live`, or we'll lose the other changes.

**Comment by kit-ty-kate** [comment]
> The ocaml-dockerfile PR needs rebasing on master before we can push this to `live`, or we'll lose the other changes.

Done but I'm not sure why Github is still saying that there is a conflict :/ the `ocaml-dockerfile` submodule on `master` is https://github.com/avsm/ocaml-dockerfile/commit/617dbf75e53331a6e04e7e8c000c5cfcb5ea2c07 and I've rebased my PR on top of `ocaml-dockerfile` master (which is just above https://github.com/avsm/ocaml-dockerfile/commit/617dbf75e53331a6e04e7e8c000c5cfcb5ea2c07). Any clue?

**Comment by talex5** [comment]
This PR doesn't seem to have been rebased on the latest `master`. Its parent should be 753d0e24ad6a4aba61837e9da755f8e7476b1b7b (master) or ced6ed3500022d6ff52f91c5c89c695ce2b09f26 (live, testing the 16.04 PR), not 27f3330ae76d81bc666c2c08d229652d245887a1 (which is ancient).

**Comment by kit-ty-kate** [comment]
Oh I see, I was only looking at `ocaml-dockerfile`, I didn't know changes in `docker-base-images` would affect this. `git pull --rebase origin master` fixed the issue without any conflict.

Hopefully it should be ready now, sorry for the setbacks.

**Comment by talex5** [comment]
Deployed to `live` and building now...

**Comment by kit-ty-kate** [comment]
```
Step 14/63 : RUN git clone -b master git://github.com/ocaml/opam /tmp/opam
 ---> Using cache
 ---> eb2d5bccece0
 [...]
env PATH="`pwd`/bootstrap/ocaml/bin:$PATH" ./configure --enable-cold-check --with-0install-solver
configure: WARNING: unrecognized options: --with-0install-solver
```
mmh, I think this just hit something akin to https://github.com/ocurrent/docker-base-images/issues/104 :/

**Comment by talex5** [comment]
Hmm, yes, this line needs to include the hash of the commit it wants.

**Comment by kit-ty-kate** [comment]
This PR is ready for another round of review. Incidently it should also partly fix https://github.com/ocurrent/docker-base-images/issues/104

**Review by talex5 — COMMENTED** [review]
This is a good change, but I think there is a small problem: it will rebuild all the images every time one of the opam branches or opam-repository updates.

Having everything on the weekly schedule could help if they all line up, but they won't in general (and if someone manually rebuilds one of them they'll get out-of-sync again).

We should probably have the three commit inputs stay up-to-date, but have them all go into a snapshot box that takes a snapshot of them once a week.

**Comment by kit-ty-kate** [comment]
I spent the past week and a half trying various patches to ocurrent to make the `~schedule` argument sync properly but the best I've been able to do is to sync 2 out of 3 inputs in my test case.

So in the meantime this gets resolved, I used a single cache entry to assemble the three of them in this particular context.
This PR is ready to review again.

**Review by talex5 — APPROVED** [review]
This seems reasonable to get things unblocked. I've pushed it to `live`.

**Comment by kit-ty-kate** [comment]
oops, sorry for that. It's fixed.

**Comment by talex5** [comment]
Still doesn't work:
```
Cloning into '/tmp/opam'...
fatal: not a git repository (or any of the parent directories): .git
```
Does it work for you locally when you test it with `docker-compose up`?

**Comment by kit-ty-kate** [comment]
> Does it work for you locally when you test it with `docker-compose up`?

Sorry for that, I really have no disk space to give to docker on my local machine and until now I didn't know my dev work server had its ports open. I had never had the need to test docker-base-images locally in the past so i didn't know how to test it either. Now i know, sorry for that.

I've now tested that at least the default alpine image is built all the way and contains opam 2.1 with the 0install solver enabled.

**Pull request merged**
